#!/bin/bash
#use this file to cheange default parameters for plots

# //////////////////////////////////////////////////////////////////////////////
# Set path for general files
export pth2dems=${HOME}/Map_project/dems

export inputTopoL=${pth2dems}/ETOPO1_gr_resample01m.grd   #ETOPO1_Bed_g_gmt4.grd #ETOPO1_grcut.grd
export inputTopoB=${pth2dems}/ETOPO1_gr_resample01m.grd    #ETOPO1_Bed_g_gmt4.grd #ETOPO1_grcut.grd

# Path to logo file
export pth2logo=$HOME/Map_project/logos/DSOlogo2.eps

# Path to faults database file
export pth2faults=$HOME/Map_project/faults/NOAFaults_v1.0.gmt

# //////////////////////////////////////////////////////////////////////////////
# Path to input file directories

# Path to directory of input files *.inp
export pth2inpdir=../inp_historic/

# Path to directory of *.dat files
export pth2datdir=../gmt_files_hokada01/

# Path to directory of *.cou files
export pth2coudir=../output_files/

# Path to directory of *.disp files. GPS displacements
export pth2gpsdir=../gps_data/

# Path to earthquakes database
export pth2eqdir=../earthquake_data/

# pth2gpsfile=${inputdata}.disp
#pth2inpdata=../input_zakynthos/${inputfile}.inp


# //////////////////////////////////////////////////////////////////////////////
# Colormap Palettes
export landcpt=tmp_land.cpt
export bathcpt=tmp_bath.cpt
export coulombcpt=Coulomb_anatolia.cpt

# //////////////////////////////////////////////////////////////////////////////
# Only frame nust set in this section
# minlon=20.2
# maxlon=20.9
# minlat=37.9
# maxlat=38.5
# prjscale=500000
export frame=0.5		## Default 0.5

# //////////////////////////////////////////////////////////////////////////////
# scale variables

export barrange=1		## Default 1

export dhscale=100		## Default 100
export dvscale=100		## Default 100

export dhscmagn=10 #use mm
export dvscmagn=12 #use mm

# export CALC_DEPTH=8 #use km

# //////////////////////////////////////////////////////////////////////////////
export logogmt_pos="-UBL/0.05c/0.05c/DemAnast"
export logocus_pos="-Dx13.57c/10.05c+w1.1c"
# legendc="-Jx1i -R0/8/0/8 -Dx18.5c/12.6c/3.6c/3.5c/BL"	
# 